#!/bin/sh
[ ! "$(pgrep -x cmus)" ] && exit 1

artist=$(cmus-remote -Q |  \
    awk '/tag artist/ {gsub("tag artist ", "");print}')

title=$(cmus-remote -Q | \
    awk '/tag title/ {gsub("tag title ", "");print}')

[ -z "$artist" ] && [ -z "$title" ] && printf "%s" "n/a" && exit 0

stat=$(cmus-remote -Q | \
    awk '/status/ {gsub("status ", "");print}' | tr '[:lower:]' '[:upper:]')

volume="$(cmus-remote -Q | \
    awk '/set vol_left/ {print $3}')%"

line="$artist - $title"

[ "${#line}" -gt 35 ] && \
    line="$(echo "$line" | cut -c 1-30 )..."

[ "$stat" = "PLAYING" ] && \
	printf "%s" "$line $volume" || printf "%s" "$stat" 
