#!/bin/bash
isMute="$(pactl list sinks | awk '/Mute/ {print $2}' | head -n "$(( SINK + 1 ))" )"
if [ "$isMute" = "no" ]; then
    pSink="$(pactl list sinks | \
        awk -F " = " '/device.profile.description/ {print $2}' | head -n "$(( SINK + 1 ))" | \
        sed 's/["(|)"]//g; s/Digital /D-/g; s/Analog /A-/g; s/Stereo/S/g; s/Surround/SR/g'): "

    pVol="$(pactl list sinks | \
        grep '^[[:space:]]Volume:' | head -n "$(( SINK + 1 ))" | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )%"

    if [ -n "$pVol" ] && [ -n "$pSink" ]; then
        printf '%s' "$pSink$pVol"
    else
        printf '%s' "n/a"
    fi
else
    printf '%s' "Muted"
fi
