#!/usr/bin/env bash

IS_MUTE="$(pactl list sinks | grep '^[[:space:]]Mute:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' | awk '{ print $2}')"

if [ "$IS_MUTE" = "no" ]; then
    P_VOL="VOL: $(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')%"
else
    P_VOL="MUTED"
fi

if pgrep -u $UID -x cmus >/dev/null ; then C_VOL="C-VOL: $(cmus-remote -Q | grep -a '^set vol_left' | awk '{gsub("set vol_left ", "");print}')% " ; fi

printf '%s' "$C_VOL$P_VOL"
