#!/usr/bin/env dash
IWGETID=$(whereis iwgetid | awk '{print $2}') # just because iwgetid in debian is located in /usr/sbin
strength=$(awk 'NR==3 {printf "%.0f", $3*10/7}' /proc/net/wireless) ; essid=$(${IWGETID} wlp3s0 --raw) ; if [ -z "$essid" ]; then printf '%s' "" ; else printf '%s' "${essid}: ${strength}%" ; fi
