#! /bin/sh

if ps -C cmus > /dev/null; then
  echo "null";

else
volume=`cmus-remote -Q |
grep --text '^set vol_left' |
sed '/^set vol_leftsort/d' |
awk '{gsub("set vol_left ", "");print}'`

echo "C-Vol: $volume%"

fi
