#! /bin/sh

if ! pgrep -u $UID -x cmus >/dev/null; then
  echo "𝌀"

else
  echo ": $(cmus-remote -Q | grep --text '^set vol_left' | sed '/^set vol_leftsort/d' | awk '{gsub("set vol_left ", "");print}')"

fi
