#!/bin/bash 

if status=$(pamixer --get-mute)=true; then
  echo " " && exit

else
  vol=$(pamixer --get-volume)
fi

if ! pgrep -u $UID -x cmus >/dev/null; then
  cmus=""

else
  cvol=$(cmus-remote -Q | grep vol_left | cut -d ' ' -f3-)
  cmus=": $cvol% "
fi

echo "$cmus: $vol%"


#[ $(pamixer --get-mute) = true ] && echo "   " && exit
#
## if ps -C cmus > /dev/null; then
#if ! pgrep -u $UID -x cmus >/dev/null; then
#    vol="$(pamixer --get-volume)"
#    echo "|  $vol% "
#
#    else
#    vol="$(pamixer --get-volume)"
#    volume=`cmus-remote -Q | grep --text '^set vol_left' | sed '/^set vol_leftsort/d' | awk '{gsub("set vol_left ", "");print}'`
#    echo "| : $volume% | : $vol% "
#
#fi
#
